import { GoogleGenAI, Modality } from "@google/genai";

export const enhanceImage = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const imageData = base64Image.split(',')[1];
  const mimeTypeMatch = base64Image.match(/data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,/);
  if (!mimeTypeMatch) {
    throw new Error("Invalid base64 image format");
  }
  const mimeType = mimeTypeMatch[1];
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: imageData,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  const candidate = response.candidates?.[0];

  if (!candidate || !candidate.content || !candidate.content.parts) {
    if (candidate?.finishReason === 'SAFETY') {
      const blockedRating = candidate.safetyRatings?.find(rating => rating.blocked);
      throw new Error(`Image generation failed due to safety restrictions. Blocked category: ${blockedRating?.category || 'Unknown'}`);
    }
    throw new Error("The API returned an unexpected response. Please try again.");
  }

  for (const part of candidate.content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error("No image was generated by the API.");
};